### ISSUE TITLE
Feature request - Wifi Captive Portal

### ISSUE THREAD

**Issue by agsochi** [seb821/espRFLinkMQTT#1]
Hi @seb821 
Thank you for grate firmware.
Can you please add Wifi Captive Portal like[ this one](https://github.com/tzapu/WiFiManager) to your project?

And second - add web configurable MQTT server

**Comment by seb821** [comment]
Hi agsochi,
I thought about it, but it would add complexity to the code and require to spend more time on it.
Same for web configurable MQTT server : it is probably doable, but as I am not a c developer at all, every improvement requires quite a lot of time. So, I prefer to focus on other projects.
In fact, as I had spent quite some time on it, I just wanted to share my work as it could be useful to others, but I do not intend to make a firmware that will be maintained and improved regularly. 
Please be free to fork the project and improve it though.
Regards,

**Comment by seb821** [comment]
Hey,

I added MQTT web configurable server in the dev branch. 

For wifi, I did several tests but I am not very satisfied at the moment
- [Wifimanager ](https://github.com/tzapu/WiFiManager) - it uses a lot of memory
-  [ESP_WiFiManager](https://github.com/khoih-prog/ESP_WiFiManager) - it works but still use quite some memory. It can be tested in the dev branch by defining USE_WM at the beginning of config. h
- [AutoConnect](https://hieromon.github.io/AutoConnect/) - very well documented but heavy. Sometimes the web page to add a network fails to appear. It can be tested in the dev branch by defining USE_AUTOCONNECT at the beginning of config. h

**Comment by sylvaing** [comment]
nice improvement in sight !

**Comment by seb821** [comment]
Dev branch now includes a WiFi management part. 
No use of external library in order to avoid additonnal memory useage or increase firmware size.
Sequence is: ESP starts access point after 1 min if WiFi connection failed, stays in this state for 5 min to give opportunity to update WiFi settings, then returns to normal WiFi connection attempt
Please feel free to test the dev branch and comment. 
This version is probably very close to being released.

**Comment by seb821** [comment]
Implemented in dev branch. Will be available in master soon.
